package sa.com.stc.softpossimulator.model

data class SimulatorFormData(
    val selectedAction: ActionType = ActionType.REGISTRATION_STATUS,
    val resultMode: ResultMode = ResultMode.SUCCESS,
    val failureMode: FailureMode = FailureMode.DECLINED,
    val orderId: String = "ORDER-1001",
    val amount: String = "115.00",
    val rrn: String = "123456789012",
    val pan: String = "541234******1111",
    val terminalId: String = "12345678TERM0001",
    val cardName: String = "MASTERCARD",
    val authCode: String = "A12345",
    val cardExpiryDate: String = "12/28",
    val transactionRequestTime: String = "",
    val responseDescription: String = "Approved",
    val responseCode: String = "051",
    val abortReason: String = "User cancelled transaction",
    val registrationFailureCode: String = "404",
    val registrationFailureMessage: String = "Terminal is not registered",
    val refundOriginalTransactionSequenceNumber: String = "000123",
    val refundOriginalTransactionDate: String = "17-04-2026",
    val lastTransactionType: TransactionTypeOption = TransactionTypeOption.PURCHASE,
    val lastTransactionStatus: String = "Approved",
    val cardLabelName: String = "MASTERCARD",
    val authResponseCode: String = "A12345",
    val transactionResponseDate: String = "",
    val lastTransactionResponseCode: String = "00",
    val lastTransactionFailureMessage: String = "No matching transaction found",
    val reversalMessage: String = "Reversal declined",
)
